### ISSUE TITLE
Pipeline Run Error

### ISSUE THREAD

**Issue by warpdriv** [o-litnon/AzurePipelineUnityTasks#1]
Hi, Thank you for putting this together!

After setting everything up, I :

1. go into my pipeline
2. click Run pipeline
3. In the popup, I click the Run button

I get this error in the top of the popup.
/Utils/Task_Execute.yaml@templates (Line: 19, Col: 26): Unexpected value 'and(true, False)'

Can I please get some help on this error? Thank you.

**Comment by o-litnon** [comment]
A pleasure, I hope it helps!
Which build step is it failing on?
some screen shots might help if you have the pipeline run still?

**Comment by o-litnon** [comment]
I have pushed an update to the Task_Execute.yaml file:
- https://github.com/o-litnon/AzurePipelineUnityTasks/commit/340a231b431a5791f5d84de9b6b799024d95d8db

That should be working for you now if you pull the new file
(I'll close the issue for now)

**Comment by warpdriv** [comment]
Hi, the pipeline does not get that error anymore. Thank you for your quick response.
